# Local Gitlab-CI file for SDP Master

# ============================================================================
# Build python packages
# ============================================================================

build:ska-sdp-master_dev: # Executed on a commit
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/tango_sdp_master

build:ska-sdp-master:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/tango_sdp_master

# ============================================================================
# Testing built python package
# ============================================================================

test:ska-sdp-master:
  extends: .tango_tests
  stage: test
  script:
    - cd src/tango_sdp_master
    - python3 setup.py test
    - mv .coverage ../../$CI_JOB_NAME.coverage
    - mv htmlcov build/sdp_master_htmlcov
    - mv coverage.xml build/code-coverage.xml
    - mv build ../../build
  artifacts:
    paths:
      - build
      - ./$CI_JOB_NAME.coverage
    expire_in: 1 week
    when: always

## ============================================================================
## Publish python packages
## ============================================================================

publish:ska-sdp-master-dev:
  extends: .publish_python_dev
  dependencies:
    - build:ska-sdp-master_dev
  variables:
    BUILD_PATH: src/tango_sdp_master

publish:ska-sdp-master:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-master
  variables:
    BUILD_PATH: src/tango_sdp_master

## ============================================================================
## Build, tag and push Docker development images
## ============================================================================

# This needs to be updated. Might be best to use Gitlab registry for
# development images, otherwise it will load the nexus registry with lots of
# development images.

# Build and push `tangods_sdp_master` image.
build:tangods_sdp_master:
  stage: build
  extends: .build_docker
  variables:
    BUILD_PATH: src/tango_sdp_master

### ============================================================================
### Test Docker development images
### ============================================================================
#
## Placeholder for testing. Currently not doing anything.
# test:tangods_sdp_master:
#  stage: test
#  extends: .pull_docker
#  variables:
#    BUILD_PATH: src/tango_sdp_master
#  script:
#    - echo "Placeholder for testing docker images"

## ============================================================================
## Tag and push Docker latest images (master only)
## ============================================================================

publish:tangods_sdp_master:
  extends: .publish_template
  dependencies:
    - build:tangods_sdp_master
  variables:
    BUILD_PATH: src/tango_sdp_master