# Local Gitlab-CI file for SDP Master

# ============================================================================
# Build python packages
# ============================================================================

.build_python:
  stage: build
  dependencies: []
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
  tags:
    - docker
    - engageska
  artifacts:
    paths:
      - ./$BUILD_PATH/dist/

.build_python_dev:
  extends: .build_python
  dependencies: []
  script:
    - cd $BUILD_PATH
    - python setup.py egg_info -b+dev.$CI_COMMIT_SHORT_SHA sdist bdist_wheel

.build_python_release:
  extends: .build_python
  script:
    - cd $BUILD_PATH
    - python setup.py sdist bdist_wheel

build:ska-sdp-master_dev: # Executed on a commit
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/tango_sdp_master

build:ska-sdp-master:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/tango_sdp_master
  only: [master]

# ============================================================================
# Testing built python package
# ============================================================================

.tango_tests:
  stage: test
  tags: [docker]
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest

test:ska-sdp-master:
  extends: .tango_tests
  stage: test
  script:
    - cd src/tango_sdp_master
    - python3 setup.py test
    - mv .coverage ../../$CI_JOB_NAME.coverage
  artifacts:
    paths:
      - ./$CI_JOB_NAME.coverage
    expire_in: 1 week
    when: always

## ============================================================================
## Publish python packages
## ============================================================================

.publish_python:
  stage: publish
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  tags:
    - docker
    - engageska
  before_script:
    - pip install twine

.publish_python_dev:
  extends: .publish_python
  except: [master]
  script:
    - cd $BUILD_PATH
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* || true

.publish_python_release:
  extends: .publish_python
  only: [master]
  script:
    - cd $BUILD_PATH
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* || true
    - twine upload --skip-existing -u $PYPI_USER -p $PYPI_PASS dist/* || true

publish:ska-sdp-master-dev:
  extends: .publish_python_dev
  dependencies:
    - build:ska-sdp-master_dev
  variables:
    BUILD_PATH: src/tango_sdp_master

publish:ska-sdp-master:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-master
  variables:
    BUILD_PATH: src/tango_sdp_master

## ============================================================================
## Build, tag and push Docker development images
## ============================================================================

# This needs to be updated. Might be best to use Gitlab registry for
# development images, otherwise it will load the nexus registry with lots of
# development images.

# Build and push `tangods_sdp_master` image.
build:tangods_sdp_master:
  stage: build
  extends: .build_docker
  variables:
    BUILD_PATH: src/tango_sdp_master

## ============================================================================
## Test Docker development images
## ============================================================================

# Placeholder for testing. Currently not doing anything.
test:tangods_sdp_master:
  stage: test
  extends: .pull_docker
  variables:
    BUILD_PATH: src/tango_sdp_master
  script:
    - echo "Placeholder for testing docker images"

## ============================================================================
## Tag and push Docker latest images (master only)
## ============================================================================

.tangods_master_template:
  stage: publish
  extends: .push_docker
  when: always
  dependencies:
    - build:tangods_sdp_master
  variables:
    BUILD_PATH: src/tango_sdp_master

publish:tangods_sdp_master:
  extends: .tangods_master_template
  only: [master]