# Gitlab CI jobs for SDP Master Tango device

# ============================================================================
# Build Python package
# ============================================================================

# Executed on a non-master commit

build:ska-sdp-master_dev:
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/tango_sdp_master

# Executed on a master commit

build:ska-sdp-master:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/tango_sdp_master

# ============================================================================
# Test Python package
# ============================================================================

test:ska-sdp-master:
  extends: .test_python
  script:
    - cd src/tango_sdp_master
    - python3 setup.py test
    - mv .coverage ../../$CI_JOB_NAME.coverage
    - mv htmlcov build/sdp_master_htmlcov
    - mv coverage.xml build/code-coverage.xml
    - mv build ../../build
  artifacts:
    paths:
      - build
      - ./$CI_JOB_NAME.coverage
    expire_in: 1 week
    when: always

# ============================================================================
# Publish Python package (master only)
# ============================================================================

publish:ska-sdp-master:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-master
  variables:
    BUILD_PATH: src/tango_sdp_master

# ============================================================================
# Build Docker development image
# ============================================================================

build:tangods_sdp_master:
  extends: .build_docker
  variables:
    BUILD_PATH: src/tango_sdp_master

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:tangods_sdp_master:
  extends: .push_docker_nexus
  dependencies:
    - build:tangods_sdp_master
  variables:
    BUILD_PATH: src/tango_sdp_master
