# Local Gitlab-CI file for SDP Logging

.env: &env
  variables:
    BUILD_PATH: src/logging

# ============================================================================
# Build python packages
# ============================================================================

build:ska-sdp-logging_dev: # Executed on a commit
  extends: .build_python_dev
  *env

build:ska-sdp-logging:
  extends: .build_python_release
  *env

# ============================================================================
# Testing built python package
# ============================================================================

test:ska-sdp-logging:
  extends:
    - .tango_tests
    - .test_with_coverage
  *env

## ============================================================================
## Publish python packages
## ============================================================================

publish:ska-sdp-logging-dev:
  extends: .publish_python_dev
  dependencies:
    - build:ska-sdp-logging_dev
  *env

publish:ska-sdp-logging:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-logging
  *env