apiVersion: batch/v1
kind: Job
metadata:
    name: sender
    namespace: sdp
spec:
  template:
    metadata:
        labels:
           app: sender-pod
    spec:
       restartPolicy: Never
       containers:
       - name: sender
         image: nexus.engageska-portugal.pt/ska-telescope/pss-docker-centos-dev:0.0.0
         resources: 
             limits:
                 cpu: "10"
             requests:
                 cpu: "8"
         imagePullPolicy: IfNotPresent
         tty: True
  completions: 1
          
   

