stages:
  - test
  - posttest

# This can be run locally with
#    > gitlab-runner exec docker subarray_tests
subarray_tests:
    stage: test
    image:
      name: skaorca/pytango_ska_dev:latest
      entrypoint: [""]
    script:
      - python -m pytest
          --gherkin-terminal-reporter
          -vv
          --cucumber-json=cucumber.json
          src/tango_sdp_subarray
    artifacts:
      paths:
      - cucumber.json
      expire_in: 30 days
      when: always

# Update XRAY links in JIRA
xray:
  stage: posttest
  #tags: [ska]
  before_script: []
  #This line may require the magic setting of cache earlier on.
  cache: {}
  # dependencies: [test]
  # commented above out because it's breaking the build
  # https://confluence.xpand-it.com/display/public/XRAY/Import+Execution+Results+-+REST
  script:
    - 'curl -X POST --silent --show-error --fail
        "Content-Type: application/json"
        -H "Authorization: Basic $JIRA_AUTH"
        -F data=@cucumber.json
        https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  retry: 2 #In case JIRA doesn't work first time
