#
# Note: Tests can be run locally with
#   gitlab-runner exec <executor, eg. docker> <job name>
#

stages:
  - build
  - test
  - post_test
  - publish
  - pages

# ============================================================================
# Local Include Gitlab-CI Files
# ============================================================================
include:
  - local: /scripts/.gitlab-ci-common.yml
  - local: /src/tango_sdp_master/.gitlab-ci.yml
  - local: /src/tango_sdp_subarray/.gitlab-ci.yml
  - local: /src/config_db/.gitlab-ci.yml
  - local: /src/processing_controller/.gitlab-ci.yml
  - local: /src/helm_deploy/.gitlab-ci.yml
  - local: /src/vis_receive/.gitlab-ci.yml
  - local: /src/logging/.gitlab-ci.yml

# ============================================================================
# Build documentation
# ============================================================================

build_docs:
  stage: test
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - make -C docs html
  artifacts:
    paths: [docs/build/html/]
    expire_in: 1 day

# ============================================================================
# Generate test reports
# ============================================================================

## Generate combined test coverage report
#coverage_report:
#  stage: post_test
#  tags: [docker]
#  image: python:latest
#  variables:
#    TRAVIS_JOB_ID: $CI_PIPELINE_IID
#  before_script:
#    - pip install coverage
#    - pip install python-coveralls
#  script:
#    - coverage combine *.coverage
#    - coverage report
#    - coverage html
#  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)/'
##  after_script:
##    - coveralls --merge=coveralls.json
#  artifacts:
#    paths: [htmlcov/]
#    expire_in: 1 week

# ============================================================================
# Publish reports
# ============================================================================

# Generate gitlab pages.
pages:
  stage: pages
  tags: [docker]
  image: python:latest
#  dependencies: [coverage_report]
  script:
    - cp -R build public
    - mv build/sdp_subarray_htmlcov/* public
  artifacts:
    paths: [public/]

create_ci_metrics:
  stage: .post
  image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest
  when: always
  tags: [docker]
  script:
    # Gitlab CI badges creation: START
    - apt-get -y update
    - apt-get install -y curl --no-install-recommends
    - curl -s https://gitlab.com/ska-telescope/ci-metrics-utilities/raw/master/scripts/ci-badges-func.sh | sh
    # Gitlab CI badges creation: END
  artifacts:
    paths:
      - ./build

## ============================================================================
## Publish documentation (master only)
## ============================================================================




