stages:
  - test
  - posttest

subarray_tests:
    stage: test
    image: skaorca/pytango_ska_dev:latest
    script:
      - cd src/tango_sdp_subarray
      - python -m pytest --gherkin-terminal-reporter -vv --junitxml=junit.xml .
    artifacts:
      paths: [src/tango_sdp_subarray/junit.xml]
      reports:
        junit: junit.xml

# Update XRAY links in JIRA
xray:
  stage: posttest
  #tags: [ska]
  before_script: []
  #This line may require the magic setting of cache earlier on.
  cache: {}
  # dependencies: [test]
  # commented above out because it's breaking the build
  script:
    - 'curl -X POST --silent --show-error --fail
        -H "Content-Type: multipart/form-data"
        -H "Authorization: Basic $JIRA_AUTH"
        -F file=@junit.xml
        https://jira.skatelescope.org/rest/raven/1.0/import/execution/junit?testExecKey=XTP-118'
  retry: 2 #In case JIRA doesn't work first time
