#
# Note: Tests can be run locally with
#   gitlab-runner exec <executor, eg. docker> <job name>
#
stages:
  - test
  - post_test
  - docker_build
  - docker_push
  - deploy

# ============================================================================
# Run linters & tests
# ============================================================================

.tango_tests:
  stage: test
  tags: [docker]
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest

# Test the SDPSubarray device
test_subarray_device:
  extends: .tango_tests
  script:
    - ./scripts/run_test.sh
        src/tango_sdp_subarray
        --gherkin-terminal-reporter
        -vv
        --cucumber-json=cucumber.json
    - mv .coverage $CI_JOB_NAME.coverage
  artifacts:
    paths:
    - cucumber.json
    - $CI_JOB_NAME.coverage
    expire_in: 1 week

# Test the SDPMaster device.
test_master_device:
  extends: .tango_tests
  script:
    - ./scripts/run_test.sh src/tango_sdp_master
    - mv .coverage $CI_JOB_NAME.coverage
  artifacts:
    paths:
      - $CI_JOB_NAME.coverage

# Test the configuration database
config_db_tests:
    stage: test
    image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
    services:
      - name: quay.io/coreos/etcd:latest
        alias: etcd
        command:
          - /usr/local/bin/etcd
          - "--advertise-client-urls=http://0.0.0.0:2379"
          - "--listen-client-urls=http://0.0.0.0:2379"
          - "--initial-advertise-peer-urls=http://0.0.0.0:2380"
          - "--listen-peer-urls=http://0.0.0.0:2380"
          - "--initial-cluster=default=http://0.0.0.0:2380"
    variables:
      SDP_TEST_HOST: etcd
    script:
      - pipenv install etcd3-py
      - ./scripts/run_test.sh src/config_db
      - mv .coverage $CI_JOB_NAME.coverage
    artifacts:
      paths:
        - $CI_JOB_NAME.coverage

# Build documentation
build_docs:
  stage: test
  when: manual
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - make -C docs html
  artifacts:
    paths: [docs/build/html/]
    expire_in: 1 day

# ============================================================================
# Generate test reports
# ============================================================================

# Generate combined test coverage report
coverage_report:
  stage: post_test
  tags: [docker]
  image: python:latest
  before_script:
    - pip install coverage
  script:
    - coverage combine *.coverage
    - coverage report
    - coverage html
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    paths: [htmlcov/]
    expire_in: 1 week

# Update XRay links in JIRA. This is done only for the master
xray_report:
  stage: post_test
  tags: [docker]
  image: python:latest
  only: [master]
  script:
    - 'curl -X POST -H "Content-Type: application/json"
         -H "Authorization: Basic $JIRA_AUTH"
         --data @cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  retry: 2 # In case JIRA doesn't work first time

# ============================================================================
# Build docker images
# Note(1): There are some optimisations to make to this section but that will
#          also involve updating the Dockerfiles to be more friendly to caching
#          https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/
#          https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/
# Note(2): Images should be rebuild for each CI job which should be fast
#          due to build caching. This allows avoid us having to have
#          dependencies between build stages.
#          This also means that a each a PR should only update 1
#          image in a build dependency chain.
# ============================================================================

# *** Common settings for building docker images
.build_docker:
  variables:
    DOCKER_REGISTRY_HOST: $NEXUS_HOST
    DOCKER_REGISTRY_USER: $CI_PROJECT_NAME
    GIT_VERSION: ${CI_COMMIT_SHA:0:8}
  tags:
    - docker
    - engageska
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add make git
    - docker login -u $NEXUS_USER -p $NEXUS_PASS $NEXUS_HOST
  script:
    - cd $BUILD_PATH
    - make DOCKER_REGISTRY_HOST=$NEXUS_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME pull
    - make DOCKER_REGISTRY_HOST=$NEXUS_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME build
    - make DOCKER_REGISTRY_HOST=$NEXUS_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME push
  retry: 2

# Build and push the `pytango_build` image.
build:pytango_build:
  extends: .build_docker
  stage: docker_build
  when: manual
  variables:
    BUILD_PATH: docker/pytango_build

# Build and push the `pytango_base` image.
build:pytango_base:
  extends: .build_docker
  stage: docker_build
  when: manual
  variables:
    BUILD_PATH: docker/pytango_base

# Build and push the `pytango_ska_base` image.
build:pytango_ska_base:
  extends: .build_docker
  stage: docker_build
  when: manual
  variables:
    BUILD_PATH: docker/pytango_ska_base

# Build and push the `pytango_ska_dev` image.
build:pytango_ska_dev:
  extends: .build_docker
  stage: docker_build
  variables:
    BUILD_PATH: docker/pytango_ska_dev
#  only:
#    changes:
#      - $(BUILD_PATH)/*

# Build and push `tangods_sdp_master` image.
build:tangods_sdp_master:
  extends: .build_docker
  stage: docker_build
  variables:
    BUILD_PATH: src/tango_sdp_master

# Build and push `tangods_sdp_subarray` image.
build:tangods_sdp_subarray:
  extends: .build_docker
  stage: docker_build
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# ============================================================================
# Push versioned docker images (only from master & if change)
# ============================================================================

.push_docker:
  stage: docker_push
  when: manual
  variables:
    DOCKER_REGISTRY_HOST: $NEXUS_HOST
    DOCKER_REGISTRY_USER: $CI_PROJECT_NAME
    GIT_VERSION: ${CI_COMMIT_SHA:0:8}
  tags:
    - docker
    - engageska
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add make git
    - docker login -u $NEXUS_USER -p $NEXUS_PASS $NEXUS_HOST
  script:
    - cd $BUILD_PATH
    - make DOCKER_REGISTRY_HOST=$NEXUS_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME pull_default
    - make DOCKER_REGISTRY_HOST=$NEXUS_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME push_version
    - make DOCKER_REGISTRY_HOST=$NEXUS_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME push_latest
  retry: 2

push:pytango_build:
  extends: .push_docker
  dependencies:
    - build:pytango_build
  variables:
    BUILD_PATH: docker/pytango_build

push:pytango_base:
  extends: .push_docker
  dependencies:
    - build:pytango_base
  variables:
    BUILD_PATH: docker/pytango_base

push:pytango_ska_base:
  extends: .push_docker
  dependencies:
    - build:pytango_ska_base
  variables:
    BUILD_PATH: docker/pytango_ska_base

push:pytango_ska_dev:
  extends: .push_docker
  dependencies:
    - build:pytango_ska_dev
  variables:
    BUILD_PATH: docker/pytango_ska_dev

push:tangods_sdp_master:
  extends: .push_docker
  dependencies:
    - build:tangods_sdp_master
  variables:
    BUILD_PATH: src/tango_sdp_master

push:tangods_sdp_subarray:
  extends: .push_docker
  dependencies:
    - build:tangods_sdp_subarray
  variables:
    BUILD_PATH: src/tango_sdp_subarray


# ============================================================================
# Publish reports
# ============================================================================

# Generate gitlab pages.
pages:
  stage: deploy
  tags: [docker]
  only: [master]
  image: python:latest
  script:
    - cp -R htmlcov public/$CI_COMMIT_REF_NAME
  artifacts:
    paths: [public/]
