#image: "python:latest"
#before_script:
# TODO - add dependencies here
#variables:
#  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
#cache:
#  paths: [.cache/pip, venv]
#
#stages:
#  - test
#  - posttest
#test:
#  stage: test
#  script:
#    - docker run --rm -it
#        -v "$(pwd)":$(pwd)":rw
#        -w "$(pwd)"
#        --entrypoint=./scripts/run_test.sh
#        skaorca/tango_python_dev:latest
#        src/tango_scaling_test.sh
#  coverage: coveralls
#  
# Update XRAY links in JIRA
# Currently all hard-coded, and doesn't extract gherkin test from JIRA 
#xray:
#  stage: posttest
#  tags: [ska]
#  before_script: []
#  cache: {}
#  #only: [master] #disabled for testing now
#  dependencies: [test]
#  script:
#    - 'curl -X POST --silent --show-error --fail
#        -H "Content-Type: multipart/form-data"
#        -H "Authorization: Basic $JIRA_AUTH"
#        -F file=@junit.xml
#        https://jira.skatelescope.org/rest/raven/1.0/import/execution/junit?testExecKey=XTP-115'
#   retry: 2 #JIRA doesn't always work first time

