image: "python:latest"

## Set up caching as suggested by GitLab's Python template
#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#cache:
#  paths: [.cache/pip,venv]


# Note: Tests can be run locally with
#   gitlab-runner exec <executor, eg. docker> <stage name>

stages:
  - test
  - deploy

# Test the SDPSubarray device
subarray_tests:
    stage: test
    image: skaorca/pytango_ska_dev:latest
    before_script:
      - pip install pytest-pylint==0.13.0
    script:
      - ./scripts/run_test.sh
          src/tango_sdp_subarray
          --gherkin-terminal-reporter
          -vv
          --cucumber-json=cucumber.json
    artifacts:
      paths:
      - cucumber.json
      - .coverage
      expire_in: 30 days
      when: always

# Test the SDPMaster device.
# Run locally with: gitlab-runner exec docker master_tests
master_tests:
    stage: test
    image: skaorca/pytango_ska_dev:latest
    before_script:
      - pip install pytest-pylint==0.13.0
    script:
      - ./scripts/run_test.sh src/tango_sdp_master
    artifacts:
      paths:
        - .coverage

# Update XRay links in JIRA
xray:
  stage: deploy
  only:
    - master
  script:
    - 'curl -X POST -H "Content-Type: application/json"
         -H "Authorization: Basic $JIRA_AUTH"
         --data @cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  retry: 2 #In case JIRA doesn't work first time

# Publish Coverage reports
pages:
  stage: deploy
  before_script:
    - coverage html
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public/
    expire_in: 1 week
