# Note: Tests can be run locally with
#   gitlab-runner exec <executor, eg. docker> <stage name>

stages:
  - test
  - posttest

# Test the SDPSubarray device
subarray_tests:
    stage: test
    image: skaorca/pytango_ska_dev:latest
    script:
      - python -m pytest
          --gherkin-terminal-reporter
          -vv
          --cucumber-json=cucumber.json
          src/tango_sdp_subarray
    artifacts:
      paths:
      - cucumber.json
      expire_in: 30 days
      when: always

# Test the SDPMaster device
master_tests:
    stage: test
    image: skaorca/pytango_ska_dev:latest
    script:
      - python -m pytest -vv src/tango_sdp_master

# Update XRAY links in JIRA
xray:
  stage: posttest
  only:
    - master
  #tags: [ska]
  before_script: []
  #This line may require the magic setting of cache earlier on.
  cache: {}
  # dependencies: [test]
  # commented above out because it's breaking the build
  # https://confluence.xpand-it.com/display/public/XRAY/Import+Execution+Results+-+REST
  script:
    - 'curl -X POST -H "Content-Type: application/json"
         -H "Authorization: Basic $JIRA_AUTH"
         --data @cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  retry: 2 #In case JIRA doesn't work first time
