<<<<<<< HEAD
image: "python:latest"

## Set up caching as suggested by GitLab's Python template
#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#cache:
#  paths: [.cache/pip,venv]
=======
# Note: Tests can be run locally with
#   gitlab-runner exec <executor, eg. docker> <stage name>

stages:
  - test
  - deploy

# Test the SDPSubarray device
subarray_tests:
    stage: test
    image: skaorca/pytango_ska_dev:latest
    script:
      - ./scripts/run_test.sh
          --gherkin-terminal-reporter
          -vv
          --cucumber-json=cucumber.json
          src/tango_sdp_subarray
    artifacts:
      paths:
      - cucumber.json
      expire_in: 30 days
      when: always

#    > gitlab-runner exec docker sdpmaster_tests
master_tests:
    stage: test
    image:
      name: skaorca/pytango_ska_dev:latest
      entrypoint: [""]
    before_script:
      - pip install -r scripts/testing_requirements.txt
    script:
      - ./scripts/run_test.sh src/tango_sdp_master
    artifacts:
      paths: [htmlcov/]

# Update XRAY links in JIRA
xray:
  stage: posttest
  only:
    - master
  #tags: [ska]
  before_script: []
  #This line may require the magic setting of cache earlier on.
  cache: {}
  # commented above out because it's breaking the build
  # https://confluence.xpand-it.com/display/public/XRAY/Import+Execution+Results+-+REST
  script:
    - 'curl -X POST -H "Content-Type: application/json"
         -H "Authorization: Basic $JIRA_AUTH"
         --data @cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  retry: 2 #In case JIRA doesn't work first time

# 1. The Sphinx documentation (root)
# 2. All the notebooks (note that this will re-run them)
# 3. Coverage reports
pages:
  stage: deploy
  tags: [sdp]
  only: [master]
  dependencies: [sdpmaster_tests] # For coverage
  script:
    # Make Sphinx documentation
#    - pip install sphinx sphinx-rtd-theme
#    - make -C docs html
#    # Make notebooks
#    - make -j 4 -k -C iPython notebooks_html
#    # Copy all into "public"
#    - cp -R docs/_build/html public
#    # - cp -R iPython/out public/iPython
    - cp -R htmlcov public
  artifacts:
    paths: [public/]
    expire_in: 1 week