# Local GitLab CI file for Local Monitoring and Control (Tango devices)

.env: &env
  variables:
    BUILD_PATH: src/lmc

# ============================================================================
# Build Python package
# ============================================================================

build-python:ska-sdp-lmc-dev:
  extends: .build_python_dev
  <<: *env

build-python:ska-sdp-lmc:
  extends: .build_python_release
  <<: *env

# ============================================================================
# Test Python package
# ============================================================================

test:ska-sdp-lmc:
  extends:
    - .test_python
    - .test_with_coverage
  variables:
    BUILD_PATH: src/lmc
    TOGGLE_CONFIG_DB: 0
  before_script:
    - cd $BUILD_PATH
    - pip3 install -r requirements.txt -r requirements-test.txt
    - cd ../..
  after_script:
    - cd $BUILD_PATH
    - mv htmlcov ../../build/sdp_subarray_htmlcov
    - mv coverage.xml ../../build/code-coverage.xml
    - mv cucumber.json ../../build/cucumber.json

# ============================================================================
# Publish Python package
# ============================================================================

# publish-python:ska-sdp-lmc-dev:
#   extends: .publish_python_dev
#   dependencies:
#     - build-python:ska-sdp-lmc-dev
#   variables:
#     BUILD_PATH: src/lmc

publish-python:ska-sdp-lmc:
  extends: .publish_python_release
  dependencies:
    - build-python:ska-sdp-lmc
  <<: *env

# ============================================================================
# Build, tag and push Docker development images
# ============================================================================

# This needs to be updated. Might be best to use Gitlab registry for
# development images, otherwise it will load the nexus registry with lots of
# development images.

# Build and push ska-sdp-lmc image.
build-docker:ska-sdp-lmc:
  stage: build
  extends: .build_docker
  <<: *env


# ============================================================================
# Tag and push Docker latest images (master only)
# ============================================================================

publish-docker:ska-sdp-lmc:
  extends: .publish_template
  dependencies:
    - build-docker:ska-sdp-lmc
  <<: *env

# ============================================================================
# Update XRay links in JIRA automatically (master only)
# ============================================================================

xray-report:
  extends: .xray_report
  when: always
  only: [master]
  allow_failure: true
