# Local GitLab CI file for Local Monitoring and Control (Tango devices)

.env: &env
  variables:
    BUILD_PATH: src/lmc

# ============================================================================
# Build Python package
# ============================================================================

build-python:ska-sdp-lmc-dev:
  extends: .build_python_dev
  <<: *env

build-python:ska-sdp-lmc:
  extends: .build_python_release
  <<: *env

# ============================================================================
# Test Python package
# ============================================================================

test:ska-sdp-lmc:
  extends:
    - .test_python
    - .test_with_coverage
#  services:
#    - name: quay.io/coreos/etcd:latest
#      alias: etcd
#      command:
#        - /usr/local/bin/etcd
#        - "--advertise-client-urls=http://0.0.0.0:2379"
#        - "--listen-client-urls=http://0.0.0.0:2379"
#        - "--initial-advertise-peer-urls=http://0.0.0.0:2380"
#        - "--listen-peer-urls=http://0.0.0.0:2380"
#        - "--initial-cluster=default=http://0.0.0.0:2380"
  variables:
    BUILD_PATH: src/lmc
    SDP_CONFIG_HOST: etcd
    TOGGLE_CONFIG_DB: 0
  before_script:
    - cd $BUILD_PATH
    - pip3 install -r requirements.txt -r requirements-test.txt
    - cd ../..
  after_script:
    - cd $BUILD_PATH
    - mv htmlcov build/lmc_htmlcov
    - mv coverage.xml build/code-coverage.xml
    - mv cucumber.json build/cucumber.json
    - mv build ../../build

# ============================================================================
# Publish Python package (master only)
# ============================================================================

# publish-python:ska-sdp-lmc-dev:
#   extends: .publish_python_dev
#   dependencies:
#     - build-python:ska-sdp-lmc-dev
#   variables:
#     BUILD_PATH: src/lmc

publish-python:ska-sdp-lmc:
  extends: .publish_python_release
  dependencies:
    - build-python:ska-sdp-lmc
  <<: *env

# ============================================================================
# Build Docker development image
# ============================================================================

# Build and push `tangods_sdp_subarray` image.
build:tangods_sdp_subarray:
  extends: .build_docker
  <<: *env


# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:tangods_sdp_subarray:
  extends: .push_docker_nexus
  dependencies:
    - build:tangods_sdp_subarray
  <<: *env

# ============================================================================
# Upload XRay test report to JIRA (master only)
# ============================================================================

xray_report:
  extends: .xray_report
