# GitLab CI jobs for SDP Subarray Tango device

.env: &env
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# ============================================================================
# Build Python package
# ============================================================================

# Executed on a non-master commit

build:ska-sdp-subarray_dev:
  extends: .build_python_dev
  <<: *env

# Executed on a master commit

build:ska-sdp-subarray:
  extends: .build_python_release
  <<: *env

# ============================================================================
# Test Python package
# ============================================================================

test:ska-sdp-subarray:
  extends: .test_python
  variables:
    BUILD_PATH: src/tango_sdp_subarray
    TOGGLE_CONFIG_DB: 0
    TOGGLE_RECEIVE_ADDRESSES_HACK: 0
  after_script:
    # Move the coverage and unit test reports to the top level
    - mv $BUILD_PATH/.coverage $CI_JOB_NAME.coverage
    - mv $BUILD_PATH/unit-tests.xml unit-tests-${CI_JOB_NAME}.xml
    - mv $BUILD_PATH/cucumber.json cucumber.json
  artifacts:
    paths:
      - $CI_JOB_NAME.coverage
      - unit-tests-${CI_JOB_NAME}.xml
      - cucumber.json
    expire_in: 1 week
    when: always

# ============================================================================
# Publish Python package (master only)
# ============================================================================

publish:ska-sdp-subarray:
  extends: .publish_python
  dependencies:
    - build:ska-sdp-subarray
  <<: *env

# ============================================================================
# Build Docker development image
# ============================================================================

# Build and push `tangods_sdp_subarray` image.
build:tangods_sdp_subarray:
  extends: .build_docker
  <<: *env

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:tangods_sdp_subarray:
  extends: .publish_docker
  dependencies:
    - build:tangods_sdp_subarray
  <<: *env

# ============================================================================
# Upload XRay test report to JIRA (master only)
# ============================================================================

xray_report:
  extends: .xray_report
