# GitLab CI jobs for SDP Subarray Tango device

.env: &env
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# ============================================================================
# Build Python package
# ============================================================================

# Executed on a non-master commit

build:ska-sdp-subarray_dev:
  extends: .build_python_dev
  <<: *env

# Executed on a master commit

build:ska-sdp-subarray:
  extends: .build_python_release
  <<: *env

# ============================================================================
# Test Python package
# ============================================================================


#test:ska-sdp-subarray:
#  extends:
#    - .test_python
#    - .test_with_coverage
#  variables:
#    BUILD_PATH: src/tango_sdp_subarray
#    TOGGLE_CONFIG_DB: 0
#    TOGGLE_RECEIVE_ADDRESSES_HACK: 0
#  before_script:
#    - cd $BUILD_PATH
#    - pip3 install -r requirements.txt -r requirements-test.txt
#    - cd ../..
#  after_script:
#    - cd $BUILD_PATH
#    - mv htmlcov ../../build/sdp_subarray_htmlcov
#    - mv coverage.xml ../../build/code-coverage.xml
#    - mv cucumber.json ../../build/cucumber.json

# ============================================================================
# Publish Python package (master only)
# ============================================================================
# Commented out just for NOW
#publish:ska-sdp-subarray:
#  extends: .publish_python_release
#  dependencies:
#    - build:ska-sdp-subarray
#  <<: *env

# ============================================================================
# Build Docker development image
# ============================================================================

# Build and push `tangods_sdp_subarray` image.
build:tangods_sdp_subarray:
  extends: .build_docker
  <<: *env

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:tangods_sdp_subarray:
  extends: .push_docker_nexus
  dependencies:
    - build:tangods_sdp_subarray
  <<: *env

# ============================================================================
# Upload XRay test report to JIRA (master only)
# ============================================================================

xray_report:
  extends: .xray_report
