# GitLab CI jobs for SDP Subarray Tango device

# ============================================================================
# Build Python package
# ============================================================================

# Executed on a non-master commit

build:ska-sdp-subarray_dev:
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# Executed on a master commit

build:ska-sdp-subarray:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# ============================================================================
# Test Python package
# ============================================================================

test:ska-sdp-subarray:
  extends: .test_python
  variables:
    TOGGLE_CONFIG_DB: 0
    TOGGLE_RECEIVE_ADDRESSES_HACK: 0
  script:
    - cd src/tango_sdp_subarray
    - mkdir -p build/reports
    - pip3 install -r requirements.txt -r requirements-test.txt
    - python3 setup.py test
    - mv .coverage ../../$CI_JOB_NAME.coverage
    - mv htmlcov build/sdp_subarray_htmlcov
    - mv coverage.xml build/code-coverage.xml
    - mv cucumber.json build/cucumber.json
    - mv build ../../build
  artifacts:
    paths:
      - build
      - ./$CI_JOB_NAME.coverage
    expire_in: 1 week
    when: always

# ============================================================================
# Publish Python package (master only)
# ============================================================================

publish:ska-sdp-subarray:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-subarray
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# ============================================================================
# Build Docker development image
# ============================================================================

# Build and push `tangods_sdp_subarray` image.
build:tangods_sdp_subarray:
  extends: .build_docker
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:tangods_sdp_subarray:
  extends: .push_docker_nexus
  dependencies:
    - build:tangods_sdp_subarray
  variables:
    BUILD_PATH: src/tango_sdp_subarray

# ============================================================================
# Upload XRay test report to JIRA (master only)
# ============================================================================

xray_report:
  extends: .xray_report
