apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ include "dummy-workflow.fullname" . }}-etcd
  labels:
{{ include "dummy-workflow.labels" . | indent 4 }}
spec:
  size: 1
  version: "3.3"
  pod:
    antiAffinity: false
    nodeSelector: {}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
