kind: Service
apiVersion: v1
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-etcd-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  type: NodePort
  selector:
    etcd_cluster: {{ include "sdp-prototype.fullname" . }}-etcd
    app: etcd
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
