apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-workflow
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.workflow.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      {{ include "sdp-prototype.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.workflow.image }}:{{ .Values.workflow.version }}
        imagePullPolicy: {{ .Values.workflow.imagePullPolicy }}
        name: {{ .Chart.Name }}
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.etcd-host" . }}
        - name: SDP_HELM_NAMESPACE
          value: {{ quote .Values.helm_deploy.namespace }}
        {{- with .Values.workflow.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
