apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-workflow-testdynamic
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.workflow.testdynamic.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      {{ include "sdp-prototype.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.workflow.testdynamic.image }}:{{ .Values.workflow.testdynamic.version }}
        name: {{ .Chart.Name }}
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.etcd-host" . }}
        {{- with .Values.workflow.testdynamic.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- if index .Values "workflow" "testdynamic" "direct-kube-deploy" }}
      serviceAccountName: {{ include "sdp-prototype.fullname" . }}-testdynamic
{{- end }}
