apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "plasma_pipeline.fullname" . }}-plasma
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "plasma_pipeline.labels" . | indent 4 }}
spec:
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "plasma_pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - image: {{ .Values.cbf_sdp_emulator.container }}:{{ .Values.cbf_sdp_emulator.version }}
        imagePullPolicy: {{ .Values.cbf_sdp_emulator.imagePullPolicy }}
        name: plasma-store
        command: ["plasma_store", "-s", "/plasma/socket", "-m", "1000000000"]
        volumeMounts:
        - mountPath: /plasma
          name: plasma-storage-volume
      - image: {{ .Values.cbf_sdp_emulator.container }}:{{ .Values.cbf_sdp_emulator.version }}
        imagePullPolicy: {{ .Values.cbf_sdp_emulator.imagePullPolicy }}
        name: sender
        command: ["emu-send", "/input.ms", "-o", "transmission.channels_per_stream=4", "-o", "transmission.rate=147000"]
        volumeMounts:
        - mountPath: /input.ms
          name: input-ms-volume
        {{- with .Values.sender.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - image: {{ .Values.cbf_sdp_emulator.container }}:{{ .Values.cbf_sdp_emulator.version }}
        imagePullPolicy: {{ .Values.cbf_sdp_emulator.imagePullPolicy }}
        name: receiver-with-plasma-writer
        command: ["emu-recv", "-o", "transmission.channels_per_stream=4", "-o", "reception.datamodel=/input.ms", "-o", "reception.consumer=plasma_writer", "-o", "reception.plasma_path=/plasma/socket"]
        volumeMounts:
        - mountPath: /plasma
          name: plasma-storage-volume
        - mountPath: /input.ms
          name: input-ms-volume
        {{- with .Values.receiver.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - image: {{ .Values.cbf_sdp_emulator.container }}:{{ .Values.cbf_sdp_emulator.version }}
        imagePullPolicy: {{ .Values.cbf_sdp_emulator.imagePullPolicy }}
        name: plasma-processor
        command: ["plasma-mswriter", "-v", "-s", "/plasma/socket", "output.ms"]
        volumeMounts:
        - mountPath: /plasma
          name: plasma-storage-volume
        {{- with .Values.receiver.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: input-ms-volume
        {{ .Values.input.mountType }}:
        {{- with .Values.input.mountTypeOptions }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: plasma-storage-volume
        emptyDir:
          medium: Memory
  backoffLimit: 1
