apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vis-receive.fullname" . }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vis-receive.labels" . | indent 4 }}
spec:
  completions: 1
  replicas: {{ .Values.visreceive.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vis-receive.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.visreceive.container }}:{{ .Values.visreceive.version }}
        imagePullPolicy: {{ .Values.visreceive.imagePullPolicy }}
        name: {{ .Chart.Name }}
        {{- with .Values.visreceive.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 4