# Local Gitlab-CI file for SDP Config DB

# ============================================================================
# Build python packages
# ============================================================================

.build_python:
  stage: build
  dependencies: []
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
  tags:
    - docker
    - engageska
  artifacts:
    paths:
      - ./$BUILD_PATH/dist/

.build_python_dev:
  extends: .build_python
  dependencies: []
  script:
    - cd $BUILD_PATH
    - python setup.py egg_info -b+dev.$CI_COMMIT_SHORT_SHA sdist bdist_wheel

.build_python_release:
  extends: .build_python
  script:
    - cd $BUILD_PATH
    - python setup.py sdist bdist_wheel

build:ska-sdp-config_dev: # Executed on a commit
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/config_db

build:ska-sdp-config:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/config_db
  only: [master]

# ============================================================================
# Testing built python package
# ============================================================================

.tango_tests:
  stage: test
  tags: [docker]
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest

test:ska-sdp-config:
  extends: .tango_tests
  stage: test
  services:
    - name: quay.io/coreos/etcd:latest
      alias: etcd
      command:
        - /usr/local/bin/etcd
        - "--advertise-client-urls=http://0.0.0.0:2379"
        - "--listen-client-urls=http://0.0.0.0:2379"
        - "--initial-advertise-peer-urls=http://0.0.0.0:2380"
        - "--listen-peer-urls=http://0.0.0.0:2380"
        - "--initial-cluster=default=http://0.0.0.0:2380"
  variables:
    SDP_TEST_HOST: etcd
  script:
    - pipenv install -r src/config_db/requirements.txt
    - ./scripts/run_test.sh src/config_db
    - mv .coverage $CI_JOB_NAME.coverage
  artifacts:
    paths:
      - $CI_JOB_NAME.coverage


## ============================================================================
## Publish python packages
## ============================================================================

.publish_python:
  stage: publish
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  tags:
    - docker
    - engageska
  before_script:
    - pip install twine

.publish_python_dev:
  extends: .publish_python
  except: [master]
  script:
    - cd $BUILD_PATH
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* || true

.publish_python_release:
  extends: .publish_python
  only: [master]
  script:
    - cd $BUILD_PATH
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* || true
    - twine upload --skip-existing -u $PYPI_USER -p $PYPI_PASS dist/* || true

publish:ska-sdp-config-dev:
  extends: .publish_python_dev
  dependencies:
    - build:ska-sdp-config_dev
  variables:
    BUILD_PATH: src/config_db

publish:ska-sdp-config:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-config
  variables:
    BUILD_PATH: src/config_db