# Local Gitlab-CI file for SDP ConfigDB

# ============================================================================
# Build python packages
# ============================================================================

build:ska-sdp-config_dev: # Executed on a commit
  extends: .build_python_dev
  before_script:
    - python3 -m pip install etcd3-py
  variables:
    BUILD_PATH: src/config_db

build:ska-sdp-config:
  extends: .build_python_release
  before_script:
    - python3 -m pip install etcd3-py
  variables:
    BUILD_PATH: src/config_db

# ============================================================================
# Testing built python package
# ============================================================================

test:ska-sdp-config:
  extends: .tango_tests
  stage: test
  services:
    - name: quay.io/coreos/etcd:latest
      alias: etcd
      command:
        - /usr/local/bin/etcd
        - "--advertise-client-urls=http://0.0.0.0:2379"
        - "--listen-client-urls=http://0.0.0.0:2379"
        - "--initial-advertise-peer-urls=http://0.0.0.0:2380"
        - "--listen-peer-urls=http://0.0.0.0:2380"
        - "--initial-cluster=default=http://0.0.0.0:2380"
  variables:
    SDP_TEST_HOST: etcd
  before_script:
    - python3 -m pip install pytest-pycodestyle pytest-pydocstyle
  script:
    - python3 -m pip install -r src/config_db/requirements.txt
    - ./scripts/run_test.sh src/config_db
    - mv .coverage $CI_JOB_NAME.coverage
  artifacts:
    paths:
      - $CI_JOB_NAME.coverage

## ============================================================================
## Publish python packages
## ============================================================================

# publish:ska-sdp-config-dev:
#   extends: .publish_python_dev
#   dependencies:
#     - build:ska-sdp-config_dev
#   variables:
#     BUILD_PATH: src/config_db

publish:ska-sdp-config:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-config
  variables:
    BUILD_PATH: src/config_db