# Local Gitlab-CI file for Processing Controller

.env: &env
  variables:
    BUILD_PATH: src/processing_controller

## ============================================================================
## Build, tag and push Docker development images
## ============================================================================

# This needs to be updated. Might be best to use Gitlab registry for
# development images, otherwise it will load the nexus registry with lots of
# development images.

# Build and push `processing_controller` image.
build:processing_controller:
  stage: build
  extends: .build_docker
  <<: *env

test:processing_controller:
  extends:
    - .tango_tests
    - .test_with_coverage
  <<: *env

### ============================================================================
### Test Docker development images
### ============================================================================
#
## Placeholder for testing. Currently not doing anything.
# test:processing_controller:
#  stage: test
#  extends: .pull_docker
#  variables:
#    BUILD_PATH: src/processing_controller
#  script:
#    - echo "Placeholder for testing docker images"

## ============================================================================
## Tag and push Docker latest images (master only)
## ============================================================================

publish:processing_controller:
  extends: .publish_template
  dependencies:
    - build:processing_controller
  <<: *env
