# GitLab CI jobs for processing controller

.env: &env
  variables:
    BUILD_PATH: src/processing_controller

# ============================================================================
# Test Python package
# ============================================================================

test:processing_controller:
  extends:
    - .test_python
    - .test_with_coverage
  <<: *env

# ============================================================================
# Build Docker development image
# ============================================================================

build:processing_controller:
  extends: .build_docker
  <<: *env
<<<<<<< HEAD

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================
=======
>>>>>>> 60627fe9a9b6b18d99cae6f46bcc954a3ae6bada

publish:processing_controller:
  extends: .push_docker_nexus
  dependencies:
    - build:processing_controller
  <<: *env
