#
# Docker compose file that launches a device server with an SDPMaster device
#

version: '3.6'

services:
  sdp_master:
    image: skaorca/tangods_sdp_master:latest
    container_name: ${CONTAINER_NAME_PREFIX}sdp_master
    network_mode: ${NETWORK_MODE}
    environment:
      - TANGO_HOST=${TANGO_HOST}
    stdin_open: true
    command: ["1", "-v4"]
